- name: template_handler
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: cp_handler

- name: cp_handler
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
  loop: "{{ files }}"
  notify: restart

- name: restart 
  service: 
    name: "{{ package }}"
    state: restarted
    use: sysvini